### ISSUE TITLE
Use correct SQLAlchemy methods

### ISSUE THREAD

**Issue by ryabouza** [CCI-MOC/hil#308]
We should be using .one(), .count() or .exists() in many cases where we are just using .first() for DB queries.

**Comment by henn** [comment]
FYI - we currently are using a couple of methods that could be replaced by these like `_must_find()`.

Once we implement this, we should probably catch the [appropriate exceptions](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html?highlight=one#sqlalchemy.orm.query.Query.one) in the framework and display appropriate errors.

**Comment by zenhack** [comment]
I'm not sure I like the idea of replacing `_must_find` with simple calls to `one`. The thing is, currently, *any* exception thrown by SQLAlchemy is a bug. I like that property, and while we haven't written it down as a design guideline (perhaps we should have), it's been part of my mental model for how this works.

It also wouldn't be any less code -- unless we catch it somewhere up the stack and convert it into an `APIError`, it will get reported as a 500 (in addition to being a confusing error in the logs). Those helper functions are already nearly one-liners.

Replacing a lot (most?) of the calls to `first()` with `one_or_none()` would definitely make sense; we should restrict `first()` to cases where more than one is possible. I believe we've been much better about invoking `count()` or `exists()` when appropriate since this was filed, but don't know that we've cleaned up all of the old code.

We should probably change the implementation of `_assert_absent()` to use `exists()`. I don't see a method in the docs that could be used to replace it wholesale, even if we were to go with your suggestion and catch the SQLAlchemy exceptions.

**Comment by henn** [comment]
Just noticed [some Flask/SQLAlchemy methods](http://flask-sqlalchemy.pocoo.org/2.1/queries/#queries-in-views) that could help with this after #561 is merged:
* get_or_404()
* first_or_404()

**Comment by naved001** [comment]
@zenhack 

> I'm not sure I like the idea of replacing _must_find with simple calls to one. The thing is, currently, any exception thrown by SQLAlchemy is a bug.

I agree with this. Most of the places where we are using `first()` is because it can return `None` unlike `one()` which throws an error. I don't see any reason to change it

> Replacing a lot (most?) of the calls to first() with one_or_none()

I can't find one_or_none() in the docs. Can you point me to it?

> We should probably change the implementation of _assert_absent() to use exists()

I think the current `_assert_absent()` is totally fine imo. Moreover, I couldn't find exists() in the docs. And doing a `dir()` on `query...exists()` shows a ton of methods,  I was expecting it would just return a boolean.

@henn 
> get_or_404()

Get only works for searching by primary key. And that's not the case in most of our code. So this method isn't particularly helpful.

> first_or_404()

The current `first()` we are using is essentially `first_or_None`. Does this method offer any advantage?

I am kinda done making changes that I think are right; so expect a PR soon :D

**Comment by zenhack** [comment]
one_or_none:

http://docs.sqlalchemy.org/en/latest/orm/query.html?highlight=one_or_none#sqlalchemy.orm.query.Query.one_or_none
