### ISSUE TITLE
Need async error checking mechanism in API

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#427]
Currently, network operations are asynchronous, placed into a queue that  `serve_networks()` processes. Although some errors will be returned immediately to the caller (like permissions issues or invalid parameters), those resulting from the network operations currently have no way of reporting back to the user.

A mechanism for doing so, such as status polling, is needed. This could function by including a new API call and augmenting the `NetworkingAction` model with a status (like PENDING/SUCCESS/ERROR) and an error text field. If we added a completed timestamp, we could even have `serve_networks()` clean up the old entries based on some tunable period.

For this to work, we'll also need the drivers to generate parse-able exceptions. For that, please see #54.

**Comment by henn** [comment]
We're going to address this using the mechanism in https://github.com/CCI-MOC/haas/wiki/Asynchronous-operations

**Comment by zenhack** [comment]
I think instead of having a success status/cleanup timeout, it would make more sense to just delete them and have the client interpret 404 as success -- it will have already gotten receipt of successful enqueuing, so this is the only possibility.

Proposal:

* Operations that create networking actions return some kind of identifier/ticket
* Add a show_networking_action or such that shows the current state -- either pending or error. When the action completes successfully it will be removed, so this will return a 404, as above.
* add a cancel_networking_action that removes a networking action from the queue -- the primary use being to clear out failed actions. But it's just deleting a database object, so I see no reason to restrict it.
* (possibly) add a list_networking_actions that can be either per-project or system wide (the latter being admin-only).

**Comment by SahilTikale** [comment]
I and @zenhack  discussed this couple of weeks back. 
I like the proposal.

**Comment by zenhack** [comment]
Yeah, this is basically exactly what @SahilTikale and I talked about.

**Comment by xuhang57** [comment]
PR merged. Close this now. Please reopen if necessary
