### ISSUE TITLE
No show_port command

### ISSUE THREAD

**Issue by lokI8** [CCI-MOC/hil#447]
Unclear how to attain the running configuration of the switch through haas. Would like a command like "show_port" that returns the current interface mode, network identifier applied, and nics associated.

**Comment by zenhack** [comment]
Quoting Jonathan Bell (2015-06-22 14:49:45)

>    Unclear how to attain the running configuration of the switch through
>    haas. Would like a command like "show_port" that returns the current
>    interface mode, network identifier applied, and nics associated.

This will be a lot easier once my refactoring work is done (and we'll 
probably want a show_switch) or something as well.

**Comment by zenhack** [comment]
Re: show_switch, since these are polymorphic, I can think of a couple different ways of dealing with them:

1. Add a method to Switch that subclasses are required to implement, which formats the data accordingly.
2. Just show information that's common to all switches (name, type, list of ports)
3. Add a method to Switch that does (2), but let subclasses override it if they want to provide more information.

There's also a question of how much information should show_switch reveal. credentials should probably be off-limits, at least.

**Comment by henn** [comment]
Merging this with #472. Comments there included:

Useful info I can think of in `GET /switch/<switch>` would be:
* The switch type
* Every port on the switch, the NIC+Node it is connected to, and the output of `show_nic`. This could be helpful in debugging connectivity problems.

Useful info for `GET /switch` would be a list of every switch HaaS knows about (optionally recursively showing info).

RE: polymorphism, I lean towards option 2 - a generic driver-agnostic version that shows stuff from the DB. Is there important driver-specific stuff?

**Comment by zenhack** [comment]
I can't think of anything that the current drivers might want to  report; if nobody else can I'm happy with option (2) --- it's certainly the simplest. @gsilvis, @lokI8?

**Comment by henn** [comment]
@gsilvis, @loki8: any thoughts on @zenhack's comment?

We are still needing to fish this data out of the DB.

**Comment by henn** [comment]
It might also be beneficial to add port information to `show_node()` for debugging purposes.

It could then automatically be shown when one does a `show_network()` if #496 decides to include it verbatim.

**Comment by naved001** [comment]
Fixed by #767 and #780
