### ISSUE TITLE
node_delete should do more error checking

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#464]
in particular, we should require that a node is not part of a project before deleting it (this will transitively cover requirements like not being connected to a network...)

**Comment by zenhack** [comment]
Opinions: should we maybe impose the same constraint for `node_delete_nic`?

//cc @gsilvis @henn @lokI8

**Comment by henn** [comment]
That could work, or we could have cascading deletions. Doing the latter
might get complicated, though, since part of the deletion could be
resetting the switch port (an asynchronous operation).

**Comment by gsilvis** [comment]
So far we've always required deleting subcomponents first.  I'm definitely against deletion having an effect on the switch.

**Comment by henn** [comment]
It brings up the interesting problem of how we deal with switch
problems- if the switch is down and I want to move a physical cable to
another node as a workaround, I currently can't without some database
hackery. The node is connected to a nic, which is connected to a
network, which will never disconnect because the switch is down.

I could go either way, but agree with George in principle for now since
addressing switch failures is a bigger problem that should addressed.

**Comment by zenhack** [comment]
Okay, so it sounds like we're all okay with requiring everything be disconnected first (in both cases)? If so I'll go ahead and remove the discuss label. I'm tempted to mark this easy too.

**Comment by henn** [comment]
Does anyone know what will happen if I try to disconnect a network from a broken switch port? If it completes, then I agree that we should impose this restriction on both.

We've already had switch ports die, so this isn't a hypothetical issue.

**Comment by zenhack** [comment]
Related: #788.
