### ISSUE TITLE
REST API should be versioned

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#571]
There should be a version number in the REST API.

We can start with v0

**Comment by shwsun** [comment]
@henn what about we set the REST API v0.1 when we ship the HIL project, before the SoCC ddl?

**Comment by xuhang57** [comment]
Do we just get to choose whatever number as a starting point as we want? @naved001

**Comment by zenhack** [comment]
I would basically follow semver: https://semver.org/

With the exception that:

* We don't need to bother bumping the version with changes to the v0 api
* The v0 api doesn't need to be "older" than the stable apis; we can treat it as development ground rather than "pre" stabilization.
* The package versions don't have to coinside with the API versions.
* There's no patch part of the number, since we're just talking about an API.

**Comment by xuhang57** [comment]
@zenhack 👍 , sounds a good plan. I have no problem with that, will send a PR soon.

**Comment by xuhang57** [comment]
@zenhack  on a second thought, this is not a small task as I thought before. If we have the versioning, let say, `1.1`, does that mean we need to change all the rest auth url? 

For example, change `/node/<node>` to `/node/v1.1/<node>`?

**Comment by zenhack** [comment]
My thinking was to start we'd just prefix everything with `/v0`. Existing clients will basically "just work" if we add `/v0` onto the endpoint they're using; at most we might want to namespce the client library so users are specifically opting in to the version.

So we'd change `/node/<node>` to /v0/node/<node>`.

**Comment by xuhang57** [comment]
That should work well. But I don't know how to work on this at the moment.
so leave this issue open for now.

**Comment by xuhang57** [comment]
@zenhack let's say we manually add the prefix to all rest calls. What if we want to bump the version to v0.2? Then we have to manually update every one of them.

Is there some kind of variable mechanism we could use? 
For example

version = "v0"

`version + /node/<node>`
`version + /network/<network>`
`version + /project/<project>`

**Comment by zenhack** [comment]
Let me mull this over a bit; I have some half-baked ideas about how to deal with this in the server-side code, but need to think about it a bit more.

**Comment by xuhang57** [comment]
What OpenStack does: https://docs.openstack.org/nova/latest/contributor/microversions.html

**Comment by zenhack** [comment]
Yeah, the mechanism there seems conceptually equivalent, though I like putting it in the path better because it makes it impossible not to specify a version.

My question was more about how to implement the interface, in terms of python's routing and such.

One thing we could do: change `rest_call` to take an extra keyword argument specifying the api version(s) for which the call exists. `rest._rest_wrapper` will check that the version specified in the URL is compatible, only invoking the api call if so.

We could have the keyword argument default to version 0, so apis aren't stable unless we specifically mark them as such. The first patch towards this can just add a statement to rest_call `path = '/v0' + path`, and we can put the rest of the machinery in place when we actually start stabalizing things
