### ISSUE TITLE
CLI commands don't return with exit status 1 when they fail

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/hil#583]
Just noticed that my [ansible-haas script](https://github.com/knikolla/ansible-haas) was [still passing Travis CI](https://travis-ci.org/knikolla/ansible-haas/jobs/126498897#L440) even if the `haas init_db` command in the script section was failing (as it doesn't exist anymore). The CLI is exiting with 0 even if the command failed.

**Comment by henn** [comment]
@knikolla , @gsilvis - how deep should the fix for this look for errors?

The easy fix for this exact problem (running a non-existent command) is to stick a `sys.exit(1)` before the `help()` in this:
```python
    if len(sys.argv) < 2 or sys.argv[1] not in command_dict:
        # Display usage for all commands
        help()
```

Fancier would be to stick a `sys.exit(1)` for non-success in the http status check in `check_status_code()`, though something could break if the `do_*()` call wasn't the last thing done. A quick glance makes me think that doesn't happen, though.

**Comment by knikolla** [comment]
@henn I think that doesn't cover all the cases. Maybe better to put it here in the except block?

```python
def cmd(f):
    """A decorator for CLI commands.

    This decorator firstly adds the function to a dictionary of valid CLI
    commands, secondly adds exception handling for when the user passes the
    wrong number of arguments, and thirdly generates a 'usage' description and
    puts it in the usage dictionary.
    """
    @wraps(f)
    def wrapped(*args, **kwargs):
        try:
            f(*args, **kwargs)
        except TypeError:
            # TODO TypeError is probably too broad here.
            sys.stderr.write('Invalid arguements.  Usage:\n')
            help(f.__name__)
    command_dict[f.__name__] = wrapped
```

**Comment by zenhack** [comment]
Closing, since we just merged a fix.
