### ISSUE TITLE
ipmitool errors are not caught or reported

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#607]
Currently, if ipmitool fails, the user remains blissfully aware.

For example, if the IPMI `start_console` method is called, it can fail with:

```
Info: SOL payload disabled
```

However, the user is returned successful status for both the `start_console` and subsequent `show_console` calls.

To address this, HIL could check the exit status for the ipmitool calls and look for non-zero status. Added bonus if we could send the output to the error log.

**Comment by matsuuran** [comment]
@henn right now the `start_console`, `show_console`, and `stop_console` all have the same rest call `node/<nodename>/console`.  I looked through the code and don't see any real reason for this so I wanted to check with you before I changed it up

**Comment by henn** [comment]
I'd check to be sure there's a compelling reason to change the API before changing it.
REST is more object-oriented than procedural, so having all of those use do different operations on the same URL makes sense to me.

@gsilvis, @knikolla and @zenhack all have strong opinions on REST APIs. Any thoughts guys?

**Comment by zenhack** [comment]
I'd quibble with referring to it as "object oriented," but yeah, having multiple functions implement stuff at the same URL is fine. the REST-ish interpretation of this is that `/node/<nodename>/console` is the path to the node's console; `GET` gets a representation of it, 

What *is* weird is the use of PUT/DELETE; these imply setting the value of the resourc/deleting it, which isn't really what's going on here. someting like a POST or (probably better) PATCH with a body `{"state": "started"}` or such would be more rest-ish.

The API changes I made on my open console PR just get rid of start and stop entirely, though there are still some implementation questions there.

There's a certain amount of friction trying to make APIs dealing heavily with side-effects (and not just munging data around) fit into the REST paradigm, which really is designed for doucment-oriented stuff (like webpages!). I often wonder if a better approach would have been to just use an rpc layer and be done with it; I think the REST api is something we did basically because openstack was doing it, and I feel like we've spent more than enough time quibbling about what is and isn't REST to outweigh that argument. Mind you, I'm not suggesting we turn around at this point -- probably not worth the effort.

**Comment by zenhack** [comment]
Also, afaik the console functionality is still completely inoperable, no?

**Comment by matsuuran** [comment]
@zenhack if you're removing the start/stop commands is there a point in me continuing?

**Comment by zenhack** [comment]
I don't think we've really settled on what to do with that PR; there are some issues with the current implementation and I don't recall if we came to a consensus on the proposed changes to the Api. The current implementation is broken though, AFAIK, and we probably ought to decide where we want this functionality to go before doing much extra work.

**Comment by xuhang57** [comment]
@naved001  do you have a more up-to-date insight on this?

**Comment by zenhack** [comment]
We're replacing all of this with obmd, so we should probably just close this.

**Comment by xuhang57** [comment]
will look into the new obmd design spec. Close this for now. Pls reopen if necessary.
