### ISSUE TITLE
API for explicit auth checks

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#692]
As we're doing more and more integrations (BMI, Net Ex, VPN, ...), the need for services to verify that a user has access to things like a node keeps coming up.

The use case we discussed today was having a dedicated, separate console proxy service. It would need to be able to verify that a particular user had access to a node (without checking with HIL, it would have no way of knowing which nodes were in which projects if keystone were used).

Currently the way to check this would be to do something like calling show_node(), which is hacky.

I propose we have an explicit API call for these types of integrations. It could be something like `GET /node/node1/is_authorized` or something else.

**Comment by henn** [comment]
@zenhack  - do you think this would be useful for the new console service you're working on?

**Comment by zenhack** [comment]
@henn, I outlined a solution for the console stuff that I think is fairly simple and manageable. I haven't thought about it's generality, but I think something like it could be more broadly useful. It would be nice not to re-invent it over and over, if you guys are finding you need this elsewhere.

Please read the proposal (and maybe the code, since I did go ahead and implement it...) and tell me what you think of that mechanism.

**Comment by zenhack** [comment]
I feel like I've brought this up already, so maybe there's a duplicate of this issue floating around -- explicit authorization checks by third-party services are a clumsy design because very difficult to do so in a way that doesn't introduce toc-tou race conditions, which is just asking for vulnerabilities.

The orginal stated use case for this has gone in a different direction; we have a solution for the console that doesn't need it. I'm tempted to suggest closing this one. @naved001, @Izhmash, @xuhang57, thoughts?

**Comment by xuhang57** [comment]
vote for closing this and the reason is the same. 

And for BMI, it is under redesigning and I am not sure how the authentication will go. I am sure Naved would know better here.

**Comment by naved001** [comment]
Agreed.
