### ISSUE TITLE
Implement updated null switch driver

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#719]
#715 removed the null switch driver because it was out of date. It'd be good to have one for testing purposes that doesn't require configuration (the "mock" driver requires some config).

**Comment by zenhack** [comment]
I'm inclined to suggest we just close this; it's a trivial thing to add if we find ourselves wanting it when we right a particular test. The driver had bitrotten in part because we weren't using it for anything, which calls into question whether it's realy useful. If I don't hear soonish, I'll go ahead and click close.

**Comment by naved001** [comment]
I am in the favor of closing this too. For most purposes, the mock driver is good enough.
