### ISSUE TITLE
Brocade Driver: less strict error logging

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#748]
The deployment tests are failing again; even for the master (my bad; should have looked at #702 more carefully. the tests pass if you run it once, but fail when ran the second time). 

As far as I understand, the problem here is that every time a function is called again later, that according to the switch is a bad request which raises logger.error. 
For example:
When _enable_and_set_mode() is called the the second time (on the same port), it will try to re-enable switchport and the switch would say Bad Request. 

Similarly, this was when I ran the vlan_networks test. I think there was nothing to DELETE, so this was another Bad Request. 

```
haas/ext/switches/brocade.py:241: in _set_native_vlan
    self._disable_native_tag(interface)
haas/ext/switches/brocade.py:263: in _disable_native_tag
    self._make_request('DELETE', url)
haas/ext/switches/brocade.py:299: in _make_request
    logger.error('Bad Request to switch. Response: %s' % r.text)
```

@knikolla @zenhack would appreciate an extra set of eyes on this. 

I think we should change [logger.error](https://github.com/CCI-MOC/hil/blob/master/haas/ext/switches/brocade.py#L283) to logger.debug otherwise we would have to check state in every function before performing any operation.

**Comment by zenhack** [comment]
I'm nervous about toning down the error checking too much here; I'm worried about a scenario where the switch returns some error code because an operation failed, and then we plow ahead e.g. having not actually detached a network properly, giving someone unintended access to someone else's network.

Options:

1. Suck it up and add the extra check everywhere. This has the advantage that failures are loud, instead of silent, but it is a bit more work than is ideal.
2. Do as you suggest and log this stuff at a lower severity.
3. Somehow encode "acceptable" responses. maybe add a parameter to `_make_requests` that specifies a list of acceptable statuses. This way, we don't have to write explicit checks everywhere, but we find out if something fails in a way we're *not* expecting.

**Comment by naved001** [comment]
These error checks were added in #702.  

In a scenario where a switch returns an error, the networking server (`haas serve_networks`) continues to run without stopping and users wouldn't know unless they look at the logs. So raising a logging error doesn't really help as the user is unaware anyway. 

The deployment tests are failing because we are using the fixture `fail_on_log_warnings` . So the test would stop whenever loger.error is thrown, but the networking server wouldn't. 

Option (1) seems like the right way to do things, but then we may have to add more methods in the brocade driver to have extra checks which in turn might introduce some bugs. 

Option (2) is doing the things before #702 was merged but the messages by the switches are logged; which seems reasonable to me. 

For Option (3), I looked at the error codes that the switch returns. For things like re-enabling the switchport, or removing a network when it's not attached, the switch returns error codes > 400. So, as far as I understand, there doesn't seem to be a way of figuring out what is an "acceptable" response. 

@knikolla would appreciate your thoughts on this issue.

**Comment by henn** [comment]
We discussed this at the HIL weekly meeting. It sounds best to add an argument that allows the caller or make_request() to determine what to do with the error, and then verify at the callsite if the error is one we can ignore.

@knikolla @naved001 @kylehogan

**Comment by naved001** [comment]
closing this because #750 got merged.
