### ISSUE TITLE
Leasing script to work with HIL. 

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#758]
It seems we kind of need/should have a leasing script (based on feedback from people who want to use HIL on their environment). 

There is a [closed/unmerged PR](https://github.com/CCI-MOC/hil/pull/588/files) with most of the work done. Before someone picks up on this, do we need any discussion about this issue?

@zenhack @henn @SahilTikale

**Comment by zenhack** [comment]
That PR was closed because the script needed serious work, and Ravi didn't have time to work on it. I don't know that it's fair to say that it had "most of the work done."

Also, @SahilTikale's client lib is very close to being merged; it would b e good for such a script to use the library.

I'm not sure whether it makes to build on that PR or just start fresh.

I also do want to be a bit more explicit about requirements/design. It would probably save some time on the review if whoever decides to tackle this writes a brief design doc first; I'd hate to have someone spend a bunch of time implementing something only to have me have to tell them I think it was a bad idea in the first place :/

**Comment by naved001** [comment]
> I also do want to be a bit more explicit about requirements/design. It would probably save some time on the review if whoever decides to tackle this writes a brief design doc first;

Had a chat with @okrieg today, and what we want is a very basic, minimal script that sits in the `examples` folder. We'll allocate certain nodes that'll be under the control of this leasing script; and the leasing script would return the nodes from any projects to the free pool periodically. I think a lot of admin intervention will be required. This will be replaced by a full fledged scheduler (maybe quads).

@mosayyebzadeh can you add more to it from our discussion. Thanks!

**Comment by mosayyebzadeh** [comment]
@naved001 We should have a meeting for requirement/design doc soon so I can start to code the script. Can you schedule a one please?

**Comment by mosayyebzadeh** [comment]
Based on previous email I have been working on a new script. I would like to discuss about its structure before doing more coding. The functions list and the structure is like:

```python

# Takes node list as arguments
# and puts them back to free pool after given time
def release_nodes(
        hil_url, hil_username, hil_password, statusfile,
        non_persistent_list, threshold_time
        ):

# Reads current information from file for every node.
def get_project_and_time_for_node(statusfile, node):

# Updates the time for a node in file.
def update_time_for_node(
        statusfile, node,
        old_time, new_time
        ):


# Update project will be changed in
# STATUS file to match the project in HIL
def update_project_in_status_file(
        statusfile, node, new_project, old_project
        ):


# Checks the current information for the node
# and returns a tuple consisting of
# (<project_name>,List of <{"network": network-name}>, NIC name)
def get_node_current_info(hil_url, hil_username, hil_password, node):


# Takes a node ,list of {network, "network-name"} networks attached to it,
# nic on which network is attached and detaches all the networks
def detach_networks_from_node(
        hil_url, hil_username, hil_password, node, networks, node_nic
        ):


# Updates the file with project name as free and
# releases it back to free pool
def release_from_project(
        hil_url, hil_username, hil_password, statusfile, node, project
        ):

# Release a node from a project.
def release_node_from_project(
        hil_url, hil_username,
        hil_password, node, project
        ):

# Checks for free pool in the list and returns the list.
def get_free_node_list(hil_url, hil_user_name, hil_password):


if __name__ == "__main__":
        config.read("/etc/leasing.cfg")
        # config file should contain:
        # node_list, threshold, hil_url, hil_username, hil_password, statusfile

        release_nodes(
            hil_url, hil_username, hil_password,
            statusfile, node_list, threshold)

```

Any comments? @naved001 @Izhmash @SahilTikale @shwsun

**Comment by zenhack** [comment]
* You probably want to be using the client library, in which case the credentials will get passed off to that and you'll be passing around a client object instead of having multiple functions that take the url/username/password. This also has the benefit of being easy to get working with different auth backends.
* It's a little hard to tell what your intent was since there's no code and you don't actually say what type of object `statusfile` is, but: I'd define helpers for loading the file into some object (depending on the structure -- could just be a dictionary if the format is simple enough, otherwise it might make sense to define some classes) do the manipulations on that object, and then save it back to the file separately. From the sketch above it reads like you intend for each use of that statusfile variable to actually do the whole round-trip.
* What does the file format look like?

**Comment by mosayyebzadeh** [comment]
Great suggestions. Thanks.

Each line in the file will be like this: node project_name/free_pool time
Time will be compared with threshold and if it is greater than threshold the node will be released from the project.

**Comment by naved001** [comment]
#917 closes this
