### ISSUE TITLE
Driver for Dell N3048

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#760]
I am playing around with the Dell Networking N3048. It's mostly similar to the powerconnect 5548 that we support. `revert_port` is different, and the output of `_int_config` (to get interface configuration required for tests) is slightly different. Also the switch that I am playing with doesn't directly log you into privileged mode so we have to enter `enable` to do that (this is probably how the switch is configured, but we could put a check in our driver to enable privileged mode) 

So I was wondering what would be the best approach in supporting this dell switch. Should I make the current dell driver more generic by adding some `if else` and reading from the config file `[haas.ext.switches.dell]` and get the model type of the switch from there. 

Or write a separate driver derived from: 
1. `_console.py`
2. current `dell.py`
3. make a base `dell.py` and then derive 2 drivers, one for powerconnect and for this n3048. 
4. any other suggestion. 

would appreciate your thoughts @zenhack @henn

**Comment by zenhack** [comment]
Reading from the config file would be inappropriate, since that's shared by every switch, so you wouldn't be able to have both a powerconnect and an n3048 in the same setup.

These are different switch types, so we should have different classes that we differentiate based on the type field. They can share code via a superclass, and they can even be in the same extension (i.e. 2 classes defined in haas.ext.switches.dell). Exactly what makes sense depends on how different the switches are -- you probably have a better sense of that than I do, having not poked at it.

**Comment by naved001** [comment]
closing this because #772 got merged
