### ISSUE TITLE
Get rid of the lambdas sprinkled throughout CLI

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#768]
Since we're re-doing the CLI anyhow in #746 , we should get rid of the extra lambdas that are all over [cli.py](https://github.com/CCI-MOC/hil/blob/master/haas/cli.py). They're extra syntax that complicates the code, and we can get by without them.

My suggestion: stick the call dispatch from main() into a try/except block that catches `FailedAPICallException`, then get rid of check_client_response() and the lambdas.

**Comment by zenhack** [comment]
I like the notion of centralizing the error handling.

**Comment by Izhmash** [comment]
In `check_clientlib_response()` it says `except Exception as e:`.

@henn rather than using `FailedAPICallException`, should I just use `Exception`?  It would still centralize the error handling to `main()`.  

I found for instance when I typed gibberish after `haas user_delete` with `FailedAPICallException` implemented I got a long traceback with a `ValueError`.  With `Exception` instead, the report was simply `Error: No JSON object could be decoded`.

**Comment by Izhmash** [comment]
Extending the last comment, [this comparison](https://github.com/cci-moc/hil/compare/master...Izhmash:replace_lambdas) illustrates my idea to centralize the error checking and to remove the lambdas.  Is it appropriate to fully replace the two original `except` blocks in main()?

**Comment by zenhack** [comment]
I'd actually like to keep the type-specific except blocks -- if we get an error we're not expecting I want it to stand out.

**Comment by henn** [comment]
> I'd actually like to keep the type-specific except blocks --
      if we get an error we're not expecting I want it to stand out.
    I agree. In general, it's better to catch the least amount
      possible.
    Check out https://wiki.python.org/moin/HandlingExceptions

**Comment by naved001** [comment]
Fixed by #796
