### ISSUE TITLE
Decouple our HTTPClient interface from the requests library.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#777]
I was futzing around with implementing HTTPClient on top of the flask test infrastructure, and ran into a problem: HTTPClient specifies that it returns a Response object as defined by the requests library. This works for our existing implementations, since all of them ultimately shell out to requests anyway, but the flask test client doesn't, and we're using enough of the misc. helper methods provided by requests.Response that spoofing it is kindof a pain.

Regardless of what we do with the client library tests (obviously I still think we should kill the dev server), it would be good for HTTPClient to not be tightly coupled to requests. Instead, we could have it return a more minimal object that just provides accessors for status code, headers, and body -- no frills. We're using the requests library's helpers in a bunch of places, but nowhere where it would be a major inconvenience to avoid them.

//cc @henn

**Comment by zenhack** [comment]
@naved001, @knikolla, interested in your thoughts as well.

**Comment by SahilTikale** [comment]
What would we gain by doing this. Why do we need the flask test client ? I did not understand the context. Could you elaborate @zenhack.

**Comment by zenhack** [comment]
@SahilTikale, there are two things:

* I'm still of the opinion that we shouldn't be launching a real server in `tests/unit/client.py`, particularly because of the running time overhead, which makes it frustrating to use. Instead, we could pass in an HTTPClient based on flask's testing library, and have the client object use that to make requests. But
it's (very) hard to implement an HTTPClient on top of anything that doesn't ultimately use requests under
the hood.

* More of a general principle, the current design is tightly coupled to requests; it would be good to eliminate the dependency. The flask test client is just one example of how this can be constraining.

**Comment by zenhack** [comment]
Since we more or less decided at the HIL meeting that we shouldn't be launching a web server, this is actually important for the change.

**Comment by SahilTikale** [comment]
Today at HIL meeting in presence of  @henn @naved001 @okrieg @shwsun @Izhmash 
we discussed about the unit tests of client library. 

@henn mentioned that the dev server is very slow and we should move to the apache server that @knikolla had created for the integration tests. I do not mind using the apache server. I just want to make sure that it is a separate server with its own mock objects so as not to hinder other people who wish to write their test against the integration server that is currently in use. 

@henn lets respond here so as to capture the discussion and decision that we will be making on this issue.

**Comment by SahilTikale** [comment]
As to the tests being very slow, I explained the team how making changes to the fixture `create_setup` I could speed up the tests. I had a patch that was completing the tests in 45 seconds what originally took more than 5 minutes for the client library tests. But with those tests some new race conditions emerged. Largely that was because I was using the same database across all the tests to avoid the time wasted while recreating a new database for each tests. 

I mentioned that I will be exploring on how to make the unit tests self-contained by undoing the changes in the database after the tests succeeds, so as to maintain the same state of database between each test. 

@okrieg  suggested that I try to copy a vanilla populated database for each new test. I feel this could be easy to do for sqlite but I do not know how difficult can it be for postgres. 

Once the `haas` to `hil` name change is completed, I will explore this options and make a new PR to address the issue. Comments are welcome.

**Comment by zenhack** [comment]
These are *not* integration tests, we don't need a web server *at all,* regardless of whether it's apache or the dev server. Furthermore, if creating the db is the bottleneck in the sqlite tests, then gutting the http server should fix that, since we'll be able to use an in-memory db like every other test.

**Comment by zenhack** [comment]
FWIW, the client library tests are taking much *much* **much** longer than 5 minutes by themselves.

**Comment by zenhack** [comment]
Fixed by #825. I will soon submit a PR adding a flask test object implementation, and having the client lib tests use it.
