### ISSUE TITLE
Associate NetworkingActions with Ports, not Nics.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/hil#781]
Right now, the schema for NetworkignActions has a foreign key referencing the nic table. As a result, We can't do any port operations on ports that don't have an associated nic. This blocks #761.

It shouldn't be a *huge* change to have a port_id instead of a nic_id; we'd need to tweak a few other bits to match, but I don't think it would be that hard.

//cc @henn, @naved001

**Comment by naved001** [comment]
I made some [quick changes](https://github.com/CCI-MOC/hil/compare/master...naved001:port-based-networkingActions) to support this. I have associated NetworkingActions with Ports, in addition to Nics, that way I didn't have to modify all the other functions. so minimal changes. I can call revert port on a port that's not attached to a nic. 

If this approach seems reasonable, then I can finish this up otherwise I am open to other suggestions.

**Comment by zenhack** [comment]
I don't like having the redundancy, and I worry that allowing the nic to be null is going to introduce bugs.

We can probably spoof the old nic property with the `@property` decorator, and maybe even shove a deprecation warning in the getter/setter. This solves the redundancy issue, but not the null concern.

I'd also like to actually look and try to estimate how much work it would be to just update everything, and what the result would look like.

**Comment by naved001** [comment]
> I'd also like to actually look and try to estimate how much work it would be to just update everything, and what the result would look like.

I tried to estimate how much work would it be but ended updating everything. I'll make a PR soon.

**Comment by naved001** [comment]
Should we close this issue if we are going for a more generic mechanism? See this [comment](https://github.com/CCI-MOC/hil/pull/784#issuecomment-308510830)

**Comment by zenhack** [comment]
Yeah, good call. Closing.
