### ISSUE TITLE
Deal with networking action errors sanely

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#786]
Originally filed in #54, the NetworkingAction queue should properly catch switch errors and do something better than shutting down the serve_networks() daemon.

One complication is that HIL's serialization guarantees are based on the networking action queue being executed in order. If an error is encountered, it's not clear what the right thing to do is. Maybe email? Print an error on the console?

At the very least, once we have a status reporting (like #427), we can mark everything in the queue as in error state.

**Comment by zenhack** [comment]
I outlined a proposal on #427. I actually think that (plus proper monitoring/alters) might be sufficient to cover this as well, given that errors aren't something that should happen during normal system operation. Because of that it might be better not to try to gracefully degrade (and just hard fail, like we do now), since it isn't clear that there's a safe way to continue in the general case.

**Comment by naved001** [comment]
based on our discussion here https://github.com/CCI-MOC/hil/pull/929#discussion_r160087583

I think we can close this now?
