### ISSUE TITLE
Ensure that VLAN ids do not collide

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#804]
If one manually creates a network as an admin with an explicit VLAN id, then it is possible that the network ID / VLAN could collide with one in the VLAN pool.

If that were to happen, then someone else could end up with a network from the pool with the same VLAN id as the explicitly created network.

This seems like a bug to me. Can anyone think of a valid use case?
If not, then I suggest we put a check in *network_create()* that ensures a given ID is not a part of the network allocator pool, and also add an interface to the network allocator to check if an ID is in the pool.

If the network needed to be shared across projects, then HIL's network ACL support should be able to meet that need while keeping integrity.

**Comment by zenhack** [comment]
We could debate the semantics of the word "bug" -- there have historically been numerous ways for an admin to break things if not careful, and this is one. We should definitely add a check.

**Comment by naved001** [comment]
I [started working](https://github.com/CCI-MOC/hil/compare/master...naved001:unique-vlanids?expand=1) on this, and there are couple of issues that I ran into.

To make sure that VLAN ids don't collide I must mark them unavailable in the database. So, as long as the Vlan that an admin is using belongs to the allocation pool I can find it in the database and mark it unavailable (because [populate](https://github.com/CCI-MOC/hil/blob/master/hil/ext/network_allocators/vlan_pool.py#L47) adds the vlan to the database)

But if an admin uses a net_id outside of the allocation pool, then I can't mark it unavailable. If I add it to the db then it becomes a part of the regular vlan pool and hil might give out that vlan ID to some regular user. I am not sure how to handle this. (Maybe add an attribute to the Vlan class to identify if it belongs to the pool? )

Thoughts?

**Comment by zenhack** [comment]
So the situation you're concerned about is the one where hil.cfg is updated after-the-fact, to include a vlan that an admin has already manually assigned somewhere?

One thing we could do: in populate() we could check for any pre-existing networks using the same net_id that we're about to add. If we find one, we could set available = False.

**Comment by henn** [comment]
We've discussed two use cases for when an admin manually sets the VLAN for a new network:
1. When a VLAN is in the pool
2. When a VLAN is not in the pool.

The first case is the very worrisome that this issue is concerned with. For this one, we will mark the VLAN as being in use, and release it when the network is free'd. If it is in use, then we'll disallow the network create.

For the second use case, it's more debatable; I'm not convinced it's something we need to worry about anytime soon, but @SahilTikale disagrees.

**Comment by SahilTikale** [comment]
Use case 2 is covered in #817

**Comment by naved001** [comment]
#823 closes this
