### ISSUE TITLE
Create release note documenting upgrades with haas -> hil name change

### ISSUE THREAD

**Issue by henn** [CCI-MOC/hil#865]
For the 0.2 release, we need to document that:

- [ ] Since the systemd script is created manually, the old one needs to manually be deleted and the new one copied in.
- [ ]  If wanting to keep the previous `haas` user, then the script needs to be modified to reflect the different username.
- [ ] The `/var/lib/haas` and `/etc/haas.cfg` entries need to be moved (or at least symlinked)
- [ ] You should remove the "haas" version, since it will be a different set of scripts: `pip uninstall haas`
- [ ] Re-copy `hil.wsgi` and update apache's wsgi.conf entry to point to it.
- [ ] Update any scripts that have env vars (like `HAAS_ENDPOINT`) to their HIL_ varieties.

**Comment by naved001** [comment]
This checklist was helpful when upgrading engage1.

**Comment by zenhack** [comment]
This is on the 0.3 milestone (because we goofed and missed it when doing the 0.2 release); to what extent do we really want to worry about this at this point? We should be careful to document any 0.2 -> 0.3 changes needed, but I don't know whether the 0.1 -> 0.2 upgrade docs are really worth integrating at this point. I suppose if it's just a matter of pasting this checklist into a doc somewhere we should just do it.

Suggestion moving forward: Let's start a changelog file that we update as we go, so when release time comes around we don't have to step back and figure out everything that changed.

**Comment by naved001** [comment]
@zenhack I agree with everything you said.

> I suppose if it's just a matter of pasting this checklist into a doc somewhere we should just do it.

Yep, that's the plan.
