### ISSUE TITLE
Fix the CLI/client-library to print out appropriate error messages

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/hil#910]
More often than not, people get this error when using HIL "Unexpected error: No JSON object could be decoded". I think this error might be coming from the client library. This can be frustrating to deal with at times because the real error is hidden.

**Comment by naved001** [comment]
one example that I found today.

```
[centos@slurm-controller ~]$ hil show_node blah-blah
Error: Node blah-blah does not exist.

[centos@slurm-controller ~]$ hil show_node blah/blah
Unexpected error: No JSON object could be decoded
```

if there's a '/' in node name it freaks out.

**Comment by zenhack** [comment]
Here's what I assume going on in this specific case:

* putting a `/` in the node name is causing it to not match the route for that api call; we had to do something to special on the server side to get it to treat e.g. `gi1/0/2` as a single thing.
* Since the route isn't matching, the server is returning some default error page, probably a 404. Since the body isn't JSON, the client trys to parse it and freaks out.

Things we can do:

* The client should validate its arguments, so that if you pass it the name of a node, it can't be treated as anything else. We should be doing this anyway, as it might help prevent injection attacks where some tool using the client library passes in a user-supplied string to the api call.
* The client should look at the http status code, rather than just choking on the body if it's not JSON.
* The server's default error pages should return JSON, just like the errors raised explicitly by the HIL api calls.

**Comment by Izhmash** [comment]
I'll be investigating this one.

**Comment by Izhmash** [comment]
If we want users to be able to put `/` characters in their node names, we'll need to put `path:` in the API URL template, e.g. `@rest_call('GET', '/node/<path:nodename>', Schema({'nodename': basestring}))`.

Instead, would it be better to check for reserved characters and raise an error if one is detected?  That way we would prevent the 404 from causing `Unexpected error: No JSON object could be decoded`. I think it's reasonable to limit names to letters and numbers.

**Comment by Izhmash** [comment]
In the `show_node` case, we could infer that a node doesn't exist if the user tries to search for a node with a reserved character.  The same would go for switches, projects, etc.

**Comment by zenhack** [comment]
Yeah, my intention was for the client library to check and report an error itself.

**Comment by Izhmash** [comment]
I can either catch all attempts of the user to input reserved URL characters when the URL is first formed, or I can do it on a per-command basis.  For example if the user tries to search for a node with a `/` in it, HIL would report that the node could not be found.

The first solution would be simpler but less informative.

**Comment by zenhack** [comment]
Yeah, probably better to check the arguments per-call. It would probably be better to have the error indicate that `/` is illegal in node names, rather than saying the node could not be found.

**Comment by naved001** [comment]
>  I think it's reasonable to limit names to letters and numbers.

I would not limit to just letters and numbers. For instance, a lot of switch names and node names have dashes in between e.g., `cisco-05`
 `R5-PA-C01.ipmi.cluster` is a hostname for a switch which contains dots, and sometimes I just use the hostname as the switch-name itself so it's apparent to me what switch I am working with in HIL without looking into the database. 

If we are going to make a list of allowed characters in labels, then we will have to be really careful. I think just blacklist characters that could potentially cause issues.

What do you think?

**Comment by Izhmash** [comment]
I'm going to limit it to characters that are not reserved URL characters.  So, besides letters and numbers, the allowed characters will be: `$ - _ . + ! * ' ( ) ,`

**Comment by zenhack** [comment]
"No special meaning in urls" sounds like the right mwtric here.
